import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header, Footer } from "./components/HeaderFooter";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[#f5f6fa]`}
        style={{ minHeight: '100dvh', position: 'relative', paddingBottom: '60px', boxSizing: 'border-box' }}
      >
        <div className="max-w-md mx-auto min-h-screen flex flex-col bg-white relative" style={{ minHeight: '100dvh' }}>
          <Header />
          <main className="flex-1 pb-16 bg-white">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
